package io.github.avrpas.codegen;

import io.github.avrpas.ast.*;
import io.github.avrpas.ast.Operators.BinOp;
import io.github.avrpas.ast.Operators.UnOp;
import io.github.avrpas.chip.Chip;
import io.github.avrpas.config.Config;
import io.github.avrpas.config.OptimizationGoal;
import io.github.avrpas.diag.Diagnostic;
import io.github.avrpas.diag.DiagnosticReporter;
import io.github.avrpas.sema.Builtins;
import io.github.avrpas.sema.SemanticAnalyzer;
import io.github.avrpas.sema.Symbol;
import io.github.avrpas.sema.Type;

import java.util.List;

/**
 * Generates GNU avr-as compatible assembly from the type-checked AST.
 *
 * <p><b>Calling/evaluation convention.</b> Expressions evaluate to a 16-bit
 * value held in {@code r25:r24} (low byte in r24). Binary operators evaluate
 * the left operand, push it, evaluate the right operand into {@code r23:r22},
 * then pop the left back into {@code r25:r24}. Integer multiply/divide reuse
 * the standard libgcc helpers ({@code __mulhi3}, {@code __divmodhi4},
 * {@code __udivmodhi4}) so the output links cleanly with avr-gcc; when the chip
 * has a hardware multiplier and {@code --optimize speed} is set, multiply is
 * inlined with {@code mul}.</p>
 */
public final class CodeGenerator {

    private final Program program;
    private final Chip chip;
    private final Config config;
    private final DiagnosticReporter reporter;
    private final SemanticAnalyzer sema;
    private final AsmBuilder asm;

    private ProcDecl currentRoutine;
    private int labelSeq;

    // runtime-helper usage flags
    private boolean needDelayMs, needDelayUs;

    public CodeGenerator(Program program, Chip chip, Config config,
                         DiagnosticReporter reporter, SemanticAnalyzer sema) {
        this.program = program;
        this.chip = chip;
        this.config = config;
        this.reporter = reporter;
        this.sema = sema;
        this.asm = new AsmBuilder(config.emitComments);
    }

    public String generate() {
        emitHeader();
        emitVectorTable();
        emitReset();
        for (ProcDecl p : program.routines) emitRoutine(p);
        emitDataSection();
        emitRuntime();
        return asm.render();
    }

    // ---------------------------------------------------------------- header

    private void emitHeader() {
        asm.header("; ============================================================");
        asm.header("; Generated by pascal2asm-avr");
        asm.header(";   target chip : " + chip.name() + " (" + chip.family() + ")");
        asm.header(";   F_CPU       : " + config.fCpuPretty());
        asm.header(";   optimize    : " + config.optimize);
        asm.header(";   flash/sram  : " + chip.flashBytes() + " B / " + chip.sramBytes() + " B");
        if (!config.fuses.isEmpty()) asm.header(";   fuses       : " + config.fuses);
        asm.header("; Assemble & link with avr-gcc, e.g.:");
        asm.header(";   avr-gcc -mmcu=" + chip.name().toLowerCase()
                + " -nostartfiles -o out.elf " + "out.s");
        asm.header("; ============================================================");
        asm.header(".equ F_CPU, " + config.fCpuHz);
        asm.header(".equ RAMEND, " + hex(chip.ramEnd()));
    }

    // ---------------------------------------------------------- vector table

    private void emitVectorTable() {
        int count = chip.vectorCount();
        boolean useJmp = chip.hasJmpCall();
        // map vector number -> isr label
        String[] handlers = new String[count];
        for (ProcDecl p : program.routines) {
            if (p.isInterrupt()) {
                int v = chip.vectorNumber(p.interruptVector);
                if (v >= 0 && v < count) handlers[v] = "isr_" + sanitize(p.name);
            }
        }
        for (int i = 0; i < count; i++) {
            String target;
            if (i == 0) target = "__reset";
            else target = handlers[i] != null ? handlers[i] : "__bad_interrupt";
            String mn = useJmp ? ("jmp  " + target) : ("rjmp " + target);
            asm.vector(mn + (asm.commentsEnabled() ? ("\t; vector " + i) : ""));
        }
    }

    // ----------------------------------------------------------------- reset

    private void emitReset() {
        asm.lineComment("---- reset / program entry ----");
        asm.label("__reset");
        asm.insn("clr  r1", "r1 is the fixed zero register");
        asm.insn("out  0x3f, r1", "clear SREG");
        // stack pointer = RAMEND
        asm.insn("ldi  r28, lo8(RAMEND)");
        asm.insn("out  " + ioOrAddr("SPL") + ", r28", "SPL");
        if (chip.hasSfr("SPH")) {
            asm.insn("ldi  r29, hi8(RAMEND)");
            asm.insn("out  " + ioOrAddr("SPH") + ", r29", "SPH");
        }
        asm.blank();

        currentRoutine = null;
        genStmt(program.main);

        asm.blank();
        asm.label("__halt");
        asm.insn("rjmp __halt", "end of program");
        asm.blank();

        // default interrupt handler
        asm.label("__bad_interrupt");
        asm.insn("reti");
        asm.blank();
    }

    // -------------------------------------------------------------- routines

    private void emitRoutine(ProcDecl p) {
        currentRoutine = p;
        if (p.isInterrupt()) {
            emitIsr(p);
        } else {
            asm.lineComment("---- " + (p.isFunction() ? "function " : "procedure ") + p.name + " ----");
            asm.label(p.symbol.label);
            genStmt(p.body);
            if (p.isFunction()) {
                emitLoadSymbol(p.resultSymbol);
            }
            asm.insn("ret");
            asm.blank();
        }
        currentRoutine = null;
    }

    private void emitIsr(ProcDecl p) {
        asm.lineComment("---- interrupt " + p.interruptVector + " ----");
        asm.label("isr_" + sanitize(p.name));
        // save context
        asm.insn("push r0");
        asm.insn("push r1");
        asm.insn("in   r0, 0x3f", "save SREG");
        asm.insn("push r0");
        asm.insn("clr  r1");
        for (int r : new int[]{18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 30, 31}) {
            asm.insn("push r" + r);
        }
        genStmt(p.body);
        for (int i = 11; i >= 0; i--) {
            int[] regs = {18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 30, 31};
            asm.insn("pop  r" + regs[i]);
        }
        asm.insn("pop  r0");
        asm.insn("out  0x3f, r0", "restore SREG");
        asm.insn("pop  r1");
        asm.insn("pop  r0");
        asm.insn("reti");
        asm.blank();
    }

    // ------------------------------------------------------------ statements

    private void genStmt(Stmt s) {
        if (config.emitDebugInfo && s.loc.line > 0) {
            asm.comment("line " + s.loc.line);
        }
        if (s instanceof CompoundStmt) {
            for (Stmt c : ((CompoundStmt) s).statements) genStmt(c);
        } else if (s instanceof AssignStmt) {
            genAssign((AssignStmt) s);
        } else if (s instanceof IfStmt) {
            genIf((IfStmt) s);
        } else if (s instanceof WhileStmt) {
            genWhile((WhileStmt) s);
        } else if (s instanceof RepeatStmt) {
            genRepeat((RepeatStmt) s);
        } else if (s instanceof ForStmt) {
            genFor((ForStmt) s);
        } else if (s instanceof CallStmt) {
            genCall(((CallStmt) s).call, false);
        } else if (s instanceof AsmStmt) {
            for (String line : ((AsmStmt) s).lines) asm.insn(line.trim());
        } else if (s instanceof EmptyStmt) {
            // nothing
        }
    }

    private void genAssign(AssignStmt s) {
        if (s.target instanceof IndexExpr) {
            // value first, then address, then store
            eval(s.value);
            asm.insn("push r24");
            asm.insn("push r25");
            emitElementAddressToZ((IndexExpr) s.target);
            asm.insn("pop  r25");
            asm.insn("pop  r24");
            Type elem = s.target.type;
            asm.insn("st   Z, r24");
            if (elem.sizeBytes >= 2) asm.insn("std  Z+1, r25");
            return;
        }
        VarExpr v = (VarExpr) s.target;
        eval(s.value);
        emitStoreSymbol(v.symbol);
    }

    private void genIf(IfStmt s) {
        String elseL = newLabel("else");
        String endL = newLabel("endif");
        evalCondFalseJump(s.condition, s.elseBranch != null ? elseL : endL);
        genStmt(s.thenBranch);
        if (s.elseBranch != null) {
            asm.insn("rjmp " + endL);
            asm.label(elseL);
            genStmt(s.elseBranch);
        }
        asm.label(endL);
    }

    private void genWhile(WhileStmt s) {
        String top = newLabel("while");
        String end = newLabel("wend");
        asm.label(top);
        evalCondFalseJump(s.condition, end);
        genStmt(s.body);
        asm.insn("rjmp " + top);
        asm.label(end);
    }

    private void genRepeat(RepeatStmt s) {
        String top = newLabel("repeat");
        asm.label(top);
        for (Stmt c : s.body) genStmt(c);
        // loop while condition is false
        evalCondFalseJump(s.condition, top);
    }

    private void genFor(ForStmt s) {
        Symbol var = s.symbol;
        // i := from
        eval(s.from);
        emitStoreSymbol(var);
        String top = newLabel("for");
        String end = newLabel("forend");
        asm.label(top);
        // compare i with 'to'
        emitLoadSymbol(var);                 // r25:r24 = i
        asm.insn("push r24");
        asm.insn("push r25");
        eval(s.to);                          // r25:r24 = limit
        moveAccToRight();                    // r23:r22 = limit
        asm.insn("pop  r25");
        asm.insn("pop  r24");                // r25:r24 = i
        boolean signed = var.type.signed;
        // exit when (downto ? i < limit : i > limit)
        if (!s.downto) {
            // continue while i <= limit -> exit if i > limit  (limit < i)
            asm.insn("cp   r22, r24");
            asm.insn("cpc  r23, r25");
            asm.insn((signed ? "brlt " : "brlo ") + end, "exit if limit < i");
        } else {
            asm.insn("cp   r24, r22");
            asm.insn("cpc  r25, r23");
            asm.insn((signed ? "brlt " : "brlo ") + end, "exit if i < limit");
        }
        genStmt(s.body);
        // i := i +/- 1
        emitLoadSymbol(var);
        if (!s.downto) {
            asm.insn("adiw r24, 1");
        } else {
            asm.insn("sbiw r24, 1");
        }
        emitStoreSymbol(var);
        asm.insn("rjmp " + top);
        asm.label(end);
    }

    // ---------------------------------------------------- condition handling

    /** Evaluate {@code cond}; jump to {@code falseLabel} when it is false (0). */
    private void evalCondFalseJump(Expr cond, String falseLabel) {
        if (cond instanceof BinaryExpr && ((BinaryExpr) cond).op.isComparison()) {
            BinaryExpr b = (BinaryExpr) cond;
            emitComparePrep(b);
            // emit branch that jumps to falseLabel when comparison is FALSE
            emitBranchOnFalse(b, falseLabel);
            return;
        }
        // generic: evaluate to 0/1, test
        eval(cond);
        asm.insn("or   r24, r25");
        asm.insn("breq " + falseLabel);
    }

    private void emitComparePrep(BinaryExpr b) {
        eval(b.left);
        asm.insn("push r24");
        asm.insn("push r25");
        eval(b.right);
        moveAccToRight();          // right in r23:r22
        asm.insn("pop  r25");
        asm.insn("pop  r24");      // left in r25:r24
    }

    private boolean opSigned(BinaryExpr b) {
        return b.left.type.signed || b.right.type.signed;
    }

    /** After operands are in r25:r24 (left) and r23:r22 (right), branch to
     *  {@code target} when the comparison evaluates to false. */
    private void emitBranchOnFalse(BinaryExpr b, String target) {
        boolean signed = opSigned(b);
        switch (b.op) {
            case EQ:
                cp(false); asm.insn("brne " + target); break;
            case NEQ:
                cp(false); asm.insn("breq " + target); break;
            case LT: // false when left >= right
                cp(false); asm.insn((signed ? "brge " : "brsh ") + target); break;
            case GTE: // false when left < right
                cp(false); asm.insn((signed ? "brlt " : "brlo ") + target); break;
            case GT: // left > right == right < left; false when right >= left
                cp(true); asm.insn((signed ? "brge " : "brsh ") + target); break;
            case LTE: // false when right < left
                cp(true); asm.insn((signed ? "brlt " : "brlo ") + target); break;
            default:
                break;
        }
    }

    /** cp/cpc of the two operands. {@code swap}=false compares left-right. */
    private void cp(boolean swap) {
        if (!swap) {
            asm.insn("cp   r24, r22");
            asm.insn("cpc  r25, r23");
        } else {
            asm.insn("cp   r22, r24");
            asm.insn("cpc  r23, r25");
        }
    }

    // ------------------------------------------------------------ expressions

    /** Evaluate {@code e}; result left in r25:r24. */
    private void eval(Expr e) {
        if (e.isConstant() && !(e instanceof StringLiteral)) {
            loadImm16(e.constValue);
            return;
        }
        if (e instanceof VarExpr) {
            evalVar((VarExpr) e);
        } else if (e instanceof BinaryExpr) {
            evalBinary((BinaryExpr) e);
        } else if (e instanceof UnaryExpr) {
            evalUnary((UnaryExpr) e);
        } else if (e instanceof CallExpr) {
            genCall((CallExpr) e, true);
        } else if (e instanceof IndexExpr) {
            evalIndex((IndexExpr) e);
        } else if (e instanceof IntLiteral) {
            loadImm16(((IntLiteral) e).value);
        } else if (e instanceof CharLiteral) {
            loadImm16(((CharLiteral) e).value);
        } else if (e instanceof BoolLiteral) {
            loadImm16(((BoolLiteral) e).value ? 1 : 0);
        } else if (e instanceof StringLiteral) {
            emitStringAddress((StringLiteral) e);
        } else {
            asm.comment("unsupported expression -> 0");
            loadImm16(0);
        }
    }

    private void evalVar(VarExpr v) {
        if (v.builtin != null) {
            CallExpr call = new CallExpr(v.name, java.util.Collections.<Expr>emptyList(), v.loc);
            call.builtin = v.builtin;
            BuiltinCodegen.emit(this, call);
            return;
        }
        if (v.symbol != null && v.symbol.kind == Symbol.Kind.FUNCTION) {
            // zero-arg function call by bare name
            asm.insn("rcall " + v.symbol.label);
            emitLoadSymbol(v.symbol.decl.resultSymbol);
            return;
        }
        emitLoadSymbol(v.symbol);
    }

    private void evalBinary(BinaryExpr b) {
        if (b.op.isComparison()) {
            String t = newLabel("ct");
            String d = newLabel("cd");
            emitComparePrep(b);
            // produce 1 when true, else 0
            emitBranchOnTrue(b, t);
            asm.insn("ldi  r24, 0");
            asm.insn("rjmp " + d);
            asm.label(t);
            asm.insn("ldi  r24, 1");
            asm.label(d);
            asm.insn("clr  r25");
            return;
        }
        // arithmetic / bitwise / shift
        eval(b.left);
        asm.insn("push r24");
        asm.insn("push r25");
        eval(b.right);
        moveAccToRight();              // right -> r23:r22
        asm.insn("pop  r25");
        asm.insn("pop  r24");          // left  -> r25:r24
        switch (b.op) {
            case ADD: asm.insn("add  r24, r22"); asm.insn("adc  r25, r23"); break;
            case SUB: asm.insn("sub  r24, r22"); asm.insn("sbc  r25, r23"); break;
            case AND: asm.insn("and  r24, r22"); asm.insn("and  r25, r23"); break;
            case OR:  asm.insn("or   r24, r22"); asm.insn("or   r25, r23"); break;
            case XOR: asm.insn("eor  r24, r22"); asm.insn("eor  r25, r23"); break;
            case MUL: emitMul(); break;
            case DIV: case FDIV: emitDiv(opSigned(b)); break;
            case MOD: emitMod(opSigned(b)); break;
            case SHL: emitShl(); break;
            case SHR: emitShr(opSigned(b)); break;
            default: break;
        }
    }

    private void emitBranchOnTrue(BinaryExpr b, String target) {
        boolean signed = opSigned(b);
        switch (b.op) {
            case EQ:  cp(false); asm.insn("breq " + target); break;
            case NEQ: cp(false); asm.insn("brne " + target); break;
            case LT:  cp(false); asm.insn((signed ? "brlt " : "brlo ") + target); break;
            case GTE: cp(false); asm.insn((signed ? "brge " : "brsh ") + target); break;
            case GT:  cp(true);  asm.insn((signed ? "brlt " : "brlo ") + target); break;
            case LTE: cp(true);  asm.insn((signed ? "brge " : "brsh ") + target); break;
            default: break;
        }
    }

    private void emitMul() {
        if (chip.hasMul() && config.optimize == OptimizationGoal.SPEED) {
            // inline 16x16 -> 16 using the hardware multiplier
            asm.insn("mul  r24, r22", "aL*bL");
            asm.insn("movw r18, r0");
            asm.insn("mul  r24, r23", "aL*bH");
            asm.insn("add  r19, r0");
            asm.insn("mul  r25, r22", "aH*bL");
            asm.insn("add  r19, r0");
            asm.insn("clr  r1", "restore zero reg");
            asm.insn("movw r24, r18");
        } else {
            asm.insn("rcall __mulhi3", "r25:r24 = left * right");
        }
    }

    private void emitDiv(boolean signed) {
        // libgcc: dividend r25:r24, divisor r23:r22 -> quotient r23:r22
        asm.insn("rcall " + (signed ? "__divmodhi4" : "__udivmodhi4"));
        asm.insn("movw r24, r22", "quotient -> r25:r24");
    }

    private void emitMod(boolean signed) {
        // remainder is returned in r25:r24 already
        asm.insn("rcall " + (signed ? "__divmodhi4" : "__udivmodhi4"));
    }

    private void emitShl() {
        String top = newLabel("shl");
        String end = newLabel("shle");
        asm.insn("tst  r22");
        asm.insn("breq " + end);
        asm.label(top);
        asm.insn("lsl  r24");
        asm.insn("rol  r25");
        asm.insn("dec  r22");
        asm.insn("brne " + top);
        asm.label(end);
    }

    private void emitShr(boolean signed) {
        String top = newLabel("shr");
        String end = newLabel("shre");
        asm.insn("tst  r22");
        asm.insn("breq " + end);
        asm.label(top);
        asm.insn(signed ? "asr  r25" : "lsr  r25");
        asm.insn("ror  r24");
        asm.insn("dec  r22");
        asm.insn("brne " + top);
        asm.label(end);
    }

    private void evalUnary(UnaryExpr u) {
        eval(u.operand);
        switch (u.op) {
            case POS:
                break;
            case NEG:
                asm.insn("com  r25");
                asm.insn("neg  r24");
                asm.insn("sbci r25, 0xff", "two's complement negate (16-bit)");
                break;
            case NOT:
                if (u.operand.type.kind == Type.Kind.BOOLEAN) {
                    asm.insn("ldi  r18, 1");
                    asm.insn("eor  r24, r18", "logical not");
                    asm.insn("clr  r25");
                } else {
                    asm.insn("com  r24");
                    asm.insn("com  r25", "bitwise not");
                }
                break;
        }
    }

    private void evalIndex(IndexExpr ix) {
        emitElementAddressToZ(ix);
        asm.insn("ld   r24, Z");
        if (ix.type.sizeBytes >= 2) {
            asm.insn("ldd  r25, Z+1");
        } else if (ix.type.signed) {
            asm.insn("clr  r25");
            asm.insn("sbrc r24, 7");
            asm.insn("ser  r25");
        } else {
            asm.insn("clr  r25");
        }
    }

    private void emitElementAddressToZ(IndexExpr ix) {
        if (!(ix.base instanceof VarExpr)) {
            reporter.error(Diagnostic.Kind.CODEGEN, "Only simple array variables can be indexed", ix.loc);
            asm.insn("ldi  r30, 0");
            asm.insn("ldi  r31, 0");
            return;
        }
        Symbol arr = ((VarExpr) ix.base).symbol;
        int elemSize = ix.type.sizeBytes;
        eval(ix.index);
        if (elemSize == 2) {
            asm.insn("lsl  r24", "index * 2");
            asm.insn("rol  r25");
        }
        asm.insn("ldi  r30, lo8(" + arr.label + ")");
        asm.insn("ldi  r31, hi8(" + arr.label + ")");
        asm.insn("add  r30, r24");
        asm.insn("adc  r31, r25");
    }

    private void emitStringAddress(StringLiteral s) {
        String lbl = newLabel("str");
        StringBuilder bytes = new StringBuilder();
        for (int i = 0; i < s.value.length(); i++) {
            if (i > 0) bytes.append(", ");
            bytes.append((int) s.value.charAt(i));
        }
        asm.rodata(lbl + ":");
        asm.rodata("\t.byte " + bytes + (s.value.isEmpty() ? "" : ", ") + "0");
        asm.insn("ldi  r24, lo8(" + lbl + ")", "address of string in flash");
        asm.insn("ldi  r25, hi8(" + lbl + ")");
    }

    // --------------------------------------------------------- symbol access

    private void emitLoadSymbol(Symbol s) {
        if (s == null) { loadImm16(0); return; }
        if (s.kind == Symbol.Kind.CONST) {
            loadImm16(s.constValue);
            return;
        }
        if (s.isSfr) {
            if (chip.isDirectIo(s.sfrAddress)) {
                asm.insn("in   r24, " + hex(chip.ioAddress(s.sfrAddress)), s.name);
            } else {
                asm.insn("lds  r24, " + hex(s.sfrAddress), s.name);
            }
            asm.insn("clr  r25");
            return;
        }
        if (s.byRef) {
            asm.insn("lds  r30, " + s.label);
            asm.insn("lds  r31, " + s.label + "+1");
            asm.insn("ld   r24, Z");
            if (s.type.sizeBytes >= 2) {
                asm.insn("ldd  r25, Z+1");
            } else {
                extendByte(s.type.signed);
            }
            return;
        }
        asm.insn("lds  r24, " + s.label);
        if (s.type.sizeBytes >= 2) {
            asm.insn("lds  r25, " + s.label + "+1");
        } else {
            extendByte(s.type.signed);
        }
    }

    private void extendByte(boolean signed) {
        if (signed) {
            asm.insn("clr  r25");
            asm.insn("sbrc r24, 7");
            asm.insn("ser  r25", "sign-extend");
        } else {
            asm.insn("clr  r25");
        }
    }

    private void emitStoreSymbol(Symbol s) {
        if (s == null) return;
        if (s.isSfr) {
            if (chip.isDirectIo(s.sfrAddress)) {
                asm.insn("out  " + hex(chip.ioAddress(s.sfrAddress)) + ", r24", s.name);
            } else {
                asm.insn("sts  " + hex(s.sfrAddress) + ", r24", s.name);
            }
            return;
        }
        if (s.byRef) {
            asm.insn("lds  r30, " + s.label);
            asm.insn("lds  r31, " + s.label + "+1");
            asm.insn("st   Z, r24");
            if (s.type.sizeBytes >= 2) asm.insn("std  Z+1, r25");
            return;
        }
        asm.insn("sts  " + s.label + ", r24");
        if (s.type.sizeBytes >= 2) asm.insn("sts  " + s.label + "+1, r25");
    }

    /** Address of an lvalue -> r25:r24 (for var parameters). */
    private void emitLoadAddress(Expr e) {
        if (e instanceof VarExpr) {
            Symbol s = ((VarExpr) e).symbol;
            if (s.isSfr) {
                loadImm16(s.sfrAddress);
            } else if (s.byRef) {
                asm.insn("lds  r24, " + s.label, "forward pointer");
                asm.insn("lds  r25, " + s.label + "+1");
            } else {
                asm.insn("ldi  r24, lo8(" + s.label + ")");
                asm.insn("ldi  r25, hi8(" + s.label + ")");
            }
        } else if (e instanceof IndexExpr) {
            emitElementAddressToZ((IndexExpr) e);
            asm.insn("movw r24, r30");
        } else {
            reporter.error(Diagnostic.Kind.CODEGEN, "Cannot take address of this expression", e.loc);
            loadImm16(0);
        }
    }

    // ----------------------------------------------------------------- calls

    private void genCall(CallExpr c, boolean wantValue) {
        if (c.builtin != null && (c.symbol == null || c.symbol.kind == Symbol.Kind.BUILTIN)) {
            BuiltinCodegen.emit(this, c);
            return;
        }
        ProcDecl p = c.symbol.decl;
        for (int i = 0; i < p.params.size(); i++) {
            Param par = p.params.get(i);
            Expr arg = c.args.get(i);
            if (par.byRef) {
                emitLoadAddress(arg);
                asm.insn("sts  " + par.symbol.label + ", r24");
                asm.insn("sts  " + par.symbol.label + "+1, r25");
            } else {
                eval(arg);
                emitStoreSymbol(par.symbol);
            }
        }
        asm.insn("rcall " + p.symbol.label);
        if (wantValue && p.isFunction()) {
            emitLoadSymbol(p.resultSymbol);
        }
    }

    // ----------------------------------------------------------- data / bss

    private void emitDataSection() {
        if (config.alignData) asm.bss("\t.balign 2");
        for (Symbol s : sema.storage) {
            int size = s.byRef ? 2 : s.type.sizeBytes;
            if (size <= 0) size = 1;
            asm.bss("\t.lcomm " + s.label + ", " + size);
        }
    }

    // --------------------------------------------------------------- runtime

    private void emitRuntime() {
        if (needDelayMs) emitDelayMsRoutine();
        if (needDelayUs) emitDelayUsRoutine();
    }

    private void emitDelayMsRoutine() {
        long inner = Math.max(1, config.fCpuHz / 4000); // ~4 cycles per inner loop
        asm.runtime("__delay_ms:        ; r25:r24 = milliseconds");
        asm.runtime("\tsbiw r24, 0");
        asm.runtime("\tbreq 2f");
        asm.runtime("1:\tldi  r26, lo8(" + inner + ")");
        asm.runtime("\tldi  r27, hi8(" + inner + ")");
        asm.runtime("0:\tsbiw r26, 1");
        asm.runtime("\tbrne 0b");
        asm.runtime("\tsbiw r24, 1");
        asm.runtime("\tbrne 1b");
        asm.runtime("2:\tret");
    }

    private void emitDelayUsRoutine() {
        long inner = Math.max(1, config.fCpuHz / 4000000); // ~4 cycles per inner loop
        asm.runtime("__delay_us:        ; r25:r24 = microseconds");
        asm.runtime("\tsbiw r24, 0");
        asm.runtime("\tbreq 2f");
        asm.runtime("1:\tldi  r20, lo8(" + inner + ")");
        asm.runtime("0:\tdec  r20");
        asm.runtime("\tbrne 0b");
        asm.runtime("\tsbiw r24, 1");
        asm.runtime("\tbrne 1b");
        asm.runtime("2:\tret");
    }

    // ---------------------------------------------------------------- shared

    void loadImm16(long value) {
        int lo = (int) (value & 0xFF);
        int hi = (int) ((value >> 8) & 0xFF);
        asm.insn("ldi  r24, " + lo);
        asm.insn("ldi  r25, " + hi);
    }

    /** Move accumulator (r25:r24) to the right-operand register pair r23:r22. */
    private void moveAccToRight() {
        if (chip.hasMovw()) {
            asm.insn("movw r22, r24");
        } else {
            asm.insn("mov  r22, r24");
            asm.insn("mov  r23, r25");
        }
    }

    private String ioOrAddr(String sfr) {
        int addr = chip.sfrAddress(sfr);
        if (chip.isDirectIo(addr)) return hex(chip.ioAddress(addr));
        return hex(addr);
    }

    String newLabel(String base) {
        return ".L_" + base + "_" + (labelSeq++);
    }

    static String hex(int v) {
        return "0x" + Integer.toHexString(v).toUpperCase();
    }

    private static String sanitize(String name) {
        StringBuilder sb = new StringBuilder();
        for (char c : name.toCharArray()) sb.append(Character.isLetterOrDigit(c) ? c : '_');
        return sb.toString();
    }

    // accessors used by BuiltinCodegen
    public AsmBuilder asm() { return asm; }
    public Chip chip() { return chip; }
    public Config config() { return config; }
    public DiagnosticReporter reporter() { return reporter; }
    void markDelayMs() { needDelayMs = true; }
    void markDelayUs() { needDelayUs = true; }
    void evalPublic(Expr e) { eval(e); }
    void emitLoadSymbolPublic(Symbol s) { emitLoadSymbol(s); }
}
